### ISSUE TITLE
Failure: Build failed with an exception

### ISSUE THREAD

**Issue by ThomasGGoodwin** [mikroskeem/radicalaces#2]
When I was running the gradle batch file, it finished unzipping and then outputted this error.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

What should I do about this?

**Comment by mikroskeem** [comment]
I think Gradle version what this project tries to use is out of date and won't work with newer Java versions. I'll update it in a moment

**Comment by mikroskeem** [comment]
I pushed b1c99e2, you have to wait for another download but hopefully it'll work. Let me know how it goes then :smile:

**Comment by ThomasGGoodwin** [comment]
It went farther along, but then it posted this error.

* What went wrong:
Execution failed for task ':compileJava'.
> Cannot find System Java Compiler. Ensure that you have installed a JDK (not just a JRE) and configured your JAVA_HOME system variable to point to the according directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 7s
1 actionable task: 1 executed

**Comment by mikroskeem** [comment]
You need to install [JDK](https://www.google.com/search?q=java+development+kit) as Gradle suggests.

**Comment by ThomasGGoodwin** [comment]
Thank you! I've been searching for this for so long!

**Comment by mikroskeem** [comment]
If JDK install did not work for some reason then I pushed 5e659b4 to allow building this with ECJ compiler which does not require JDK presence.

`gradlew -PuseEcj`

**Comment by ThomasGGoodwin** [comment]
I set my JAVA_HOME variable correctly, and now it is giving me this.

> Task :compileJava FAILED
C:\Users\thoma\Downloads\radicalaces-master\radicalaces-master\src\main\java\eu\mikroskeem\radicalaces\applet\SimpleAppletContext.java:21: error: package sun.applet does not exist
        return audioclips.computeIfAbsent(url, key-> new sun.applet.AppletAudioClip(url));
                                                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by mikroskeem** [comment]
wew, Java 11 (I assume you picked the first result from Google) removed sun.applet.* stuff.

49979f3 should do the trick

**Comment by ThomasGGoodwin** [comment]
Sorry man, but now the build finished without any errors but now the launcher says its loading and hasn't moved from 21%.

**Comment by mikroskeem** [comment]
Heh, I think I know why... Hold on I'll get you a prebuilt jar

**Comment by mikroskeem** [comment]
https://mikroskeem.eu/stuff/radicalaces.jar

**Comment by kylemonti** [comment]
Hi everyone, bit new to Gradle so excuse my ignorance.
For those who have managed to run the game properly, was it on a Windows, Mac or Linux machine? 

Thanks,

Kyle.

**Comment by mikroskeem** [comment]
Builds for me on all those three OS-es.

**Comment by kylemonti** [comment]
> Builds for me on all those three OS-es.

Thanks for the reply. Would someone be so kind as to show me how to build this game on Gradle using Ubuntu please?

**Comment by mikroskeem** [comment]
[It's literally on the front page when you open the project link](https://github.com/mikroskeem/radicalaces/blob/master/README.md#building), but for sure there you go:

Make sure that you have Java JDK installed and then in your favourite terminal emulator, do the following:

```
git clone https://github.com/mikroskeem/radicalaces
cd radicalaces
./gradlew build
```

**Comment by kylemonti** [comment]
I had never used gradle before so I was not sure what you meant on the front page. Also I must have had some issues with the previous JDK I had installed on my Linux. 
Anyways, it worked just now, thanks a lot 😁😁😁

Bring on an android version 😆
