### ISSUE TITLE
Can't get it setup

### ISSUE THREAD

**Issue by JIGGSwashere** [mikroskeem/radicalaces#5]
Hey there, was so glad to see this here and wanted to try it out, 

I seem to be having trouble setting it up. When I run the gradlew.bat it did it's thing, downloading for a bit then gave me an error. It keeps giving the same error now but for only a split second, I'm not very knowledgeable with java and would appreciate any help given if you can.

Here's most of what the message says:
Task compileJava Failed
Build failed with an exception
Could not find Tools.jar Check that C:\blahblahblah\jre1.8.0_241 contains valid JDK
Build failed in 0s 1 actionable task: 1 executed

Thanks for your time!

**Comment by mikroskeem** [comment]
You have JRE installed instead of JDK. You have two options:
1) `gradlew.bat -PuseEcj=true` or
2) Install JDK from https://adoptopenjdk.net/

**Comment by JIGGSwashere** [comment]
Edit: Disregard this issue, I've downloaded the radicalaces.jar from the other closed thread and this one works just fine (noticed the one I had was only 84kb but the one in the other thread is a full 995kb). Thank you for your response and for preserving this great game!

**Comment by mikroskeem** [comment]
Might be related to #4
