### ISSUE TITLE
I'm confused!

### ISSUE THREAD

**Issue by UltimateHeavy** [mikroskeem/radicalaces#7]
I don't know how to get it to work after unzipping it. Could I have some help on that?

**Comment by mikroskeem** [comment]
Don't bother. [Download the jar and run that directly instead](https://github.com/mikroskeem/radicalaces/releases/tag/0.0.1)

**Comment by UltimateHeavy** [comment]
I'm sorry. I didn't know I made that comment. By the time you responded, I must've already done that.
