### ISSUE TITLE
No sound when running with Java 15 in Artix Linux

### ISSUE THREAD

**Issue by userwer** [mikroskeem/radicalaces#8]
It seems like when I run the jar in Artix (which is for the most part like Arch Linux) with the following command, I get no sound.
`java -jar radicalaces.jar`

The game runs perfectly otherwise, but in the console I see these messages, which might be relevant:
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by eu.mikroskeem.radicalaces.applet.SimpleAppletContext (file:/home/c/Downloads/radicalaces/radicalaces.jar) to method com.sun.media.sound.JavaSoundAudioClip.create(java.net.URL)
WARNING: Please consider reporting this to the maintainers of eu.mikroskeem.radicalaces.applet.SimpleAppletContext
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by mikroskeem** [comment]
Can you provide more information about your system?

How does your audio setup look like, are you using PulseAudio or plain ALSA or...? Their wiki seems to be offline right now.

**Comment by mikroskeem** [comment]
Cannot reproduce on Arch Linux with AdoptOpenJDK 15.0.1+9.

**Comment by mikroskeem** [comment]
Issue closed due to not enough information being provided.
